// rarity.js
module.exports = {
  Common: 40,
  Uncommon: 25,
  Rare: 15,
  "Rare Holo": 7,
  "Rare Holo V": 5,
  "Rare Holo GX": 5,
  "Rare Holo EX": 5,
  "Rare Holo LV.X": 4,
  "Rare Holo VMAX": 3,
  "Rare Holo VSTAR": 3,
  "Ultra Rare": 2.5,
  "Double Rare": 2.2,
  "Trainer Gallery Rare Holo": 2,
  "Illustration Rare": 1.8,
  "Special Illustration Rare": 1.5,
  "Shiny Rare": 1.2,
  "Rare Shiny": 1.2,
  "Rare Shiny GX": 1.1,
  "Shiny Ultra Rare": 1,
  "Radiant Rare": 1,
  "Rare BREAK": 0.9,
  "Rare Prime": 0.9,
  "Rare ACE": 0.8,
  "Rare Ultra": 0.7,
  "Rare Rainbow": 0.6,
  "Rare Secret": 0.5,
  "Rare Shining": 0.5,
  "Rare Holo Star": 0.4,
  "Rare Prism Star": 0.4,
  "Hyper Rare": 0.3,
  "Amazing Rare": 0.2,
  "Classic Collection": 0.15,
  Promo: 0.1,
  LEGEND: 0.05,
  "Special Illustration Rare": 0.04,
  "Unknown": 20,
};
